clc; clear all; close all;


lambda = 1; 
shellsize = lambda;      %temporary space to carve out the dielectric shell
N = 50;                 %number of pixels in which space is broken
x1    = linspace(-shellsize,shellsize,N);   %x-space of square space
y1    = linspace(-shellsize,shellsize,N);   %y-space of square space
[X Y] = meshgrid(x1,y1);
X     = reshape(X,[(N)^2,1]);           %to generate the coordinate system
Y     = reshape(Y,[(N)^2,1]);           %to generate the coordinate system

%plotting the square space
 scatter(X,Y,'k','filled');
 hold on; grid on; axis('equal','tight');

%carving out dielectric shell from the square space generated by X and Y
t = 0;      %temporary variable to hold index 
for m = 1:(N)^2
    if ((X(m)^2 + Y(m)^2) <= (0.3*lambda)^2) && ((X(m)^2 + Y(m)^2) >= (0.25*lambda)^2)
       t = t + 1; 
       X1(t) = X(m);
       Y1(t) = Y(m);
    end
end


%plotting the dielectric shell
for i = 1:length(X1)
    scatter(X1(i),Y1(i),'red','filled');
    pause(1)
end
set(gca,'fontsize',20) 